name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  PAGODA_CONSOLE_URL: https://developer-console-api-prod-k2zt32g7mq-ue.a.run.app
  CONTRACT_WASM_PATH: contracts/nft-series/nft-series.wasm
  FRONTEND_PACKAGE_NAME: NFT Collectibles Frontend
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          TEMP_SECRET="${{secrets.PAGODA_CONSOLE_TOKEN}}"
          TEMP=$(echo ${TEMP_SECRET:6} | base64 --decode)
          echo "GITHUB_REPO_FULL_NAME=$(echo ${TEMP%:*})" >> $GITHUB_ENV
    
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install 🔧
        run: |
          npm install --frozen-lockfile
      
      - name: Build Contract 🔧
        run: |
          # npm run build:contract
          echo "Contract is pre-built!"
      - name: Upload File
        id: upload
        uses: jon-lewis/upload-file-action@master
        with:
          url: '${{ env.PAGODA_CONSOLE_URL }}/deploys/deployWasm'
          forms: '{"githubRepoFullName":"${{ env.GITHUB_REPO_FULL_NAME }}","commitMessage": "${{ github.event.head_commit.message }}", "commitHash": "${{ github.sha }}"}'
          customHeaders: '{"Authorization": "${{ secrets.PAGODA_CONSOLE_TOKEN }}"}'
          fileForms: '{"main.wasm":"${{ env.CONTRACT_WASM_PATH }}"}'
            
      - name: Build Frontend 🔧
        run: |
          cd frontend
          npx next build
          npx next export
        env:
          NEXT_PUBLIC_NFT_CONTRACT_NAME: "${{ fromJson(steps.upload.outputs.output).data.contractDeployments[0].contractDeployConfig.nearAccountId }}"
          # NEXT_PUBLIC_WEB3_STORAGE_AUTH_TOKEN: TODO add your own API token from https://web3.storage to upload files to IPFS directly from the app

      - name: Upload Frontend
        id: uploadFrontend
        uses: jon-lewis/upload-directory-action@master
        with:
          url: '${{ env.PAGODA_CONSOLE_URL }}/ipfs/add'
          forms: '{}'
          customHeaders: '{"Authorization": "${{ secrets.PAGODA_CONSOLE_TOKEN }}"}'
          directory: frontend/out

      - name: Update frontend url
        id: update-frontend-url
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.PAGODA_CONSOLE_URL }}/deploys/addFrontend'
          method: 'POST'
          data: '{"repoDeploymentSlug": "${{ fromJson(steps.upload.outputs.output).data.slug }}", "cid": "${{ fromJson(steps.uploadFrontend.outputs.output).data.cid }}", "packageName": "${{ env.FRONTEND_PACKAGE_NAME }}" }'
          customHeaders: '{"Authorization": "${{ secrets.PAGODA_CONSOLE_TOKEN }}"}'
