---
name: Lint and Format Check

on:
  push:
  pull_request:
  schedule:
    - cron: "30 1 * * 0"

jobs:
  linter:
    name: Running linters
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Format and lint check
        run: npm run prettier:check && npm run lint
